Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Anderson Silva Vanin
// Descrição   : Converte Fº em Cº
// Autor(a)    : Alan Gomes Da Silva
// Data atual  : 14/03/2021
Var
// Seção de Declarações das variáveis 

tc: real
tf: real

inicio

escreval("Digite a temperatura em Fº:")
leia(tf)

tc <- 5*(tf-32)/9

escreval("A temperatura em Cº é: ", tc)

Fimalgoritmo